### ISSUE TITLE
Check for unclosed quotes

### ISSUE THREAD

**Issue by walshbr** [walshbr/woolf#5]
If we start using this on a much larger corpus the spot checks aren't going to be feasible - we'd need to have the script toss flags if the quoted material is off. One way to do this would be to make sure there is an even number of quotations in the text. That wouldn't catch every instance, but it would catch some at least. Another possibility might be for it to flag anything with more than 20 or 30% quoted material, since an unclosed quote causes spikes in the percentage of the text that appears to be quoted.

**Comment by bmw9t** [comment]
Also check to make sure the last match equals the last quotation.
